@startuml

object Minimarket
Minimarket : name  : La_Ecónomica
Minimarket : Int   : id
Minimarket : Int   : Nit
Minimarket : String: Resolución 



object Proveedores
Proveedores : name   : Nutresa
Proveedores : Int    : id
Proveedores : Int    : Nit
Proveedores : String : Cliente
Proveedores : String : Dirección
Proveedores : String : Productos
Proveedores : float  : Precio_Unitario
Proveedores : Int    : Unidades
Proveedores : Int    : Total

Minimarket--* Proveedores

@enduml


